### ISSUE TITLE
Falta el interprete en la primer linea

### ISSUE THREAD

**Issue by RomiNahir** [INTA-Radar/radar-cmd#1]
Para poder correrlo como comando  tiene que estar la ruta del interprete
Sino al instalarlo como comando:

  sudo ln -s ~/radar-cmd/Procesador/radar-cmd.py /usr/bin/

Da los siguientes errores:

$ radar-cmd.py
/usr/bin/radar-cmd.py: línea 2: __author__: orden no encontrada
/usr/bin/radar-cmd.py: línea 3: __version__: orden no encontrada
/usr/bin/radar-cmd.py: línea 4: __maintainer__: orden no encontrada
/usr/bin/radar-cmd.py: línea 5: __email__: orden no encontrada
/usr/bin/radar-cmd.py: línea 6: __status__: orden no encontrada
from: can't read /var/mail/RadarDataProcesor
/usr/bin/radar-cmd.py: línea 14: class: orden no encontrada
/usr/bin/radar-cmd.py: línea 15: HEADER: orden no encontrada
/usr/bin/radar-cmd.py: línea 16: OKBLUE: orden no encontrada
/usr/bin/radar-cmd.py: línea 17: OKGREEN: orden no encontrada
/usr/bin/radar-cmd.py: línea 18: WARNING: orden no encontrada
/usr/bin/radar-cmd.py: línea 19: FAIL: orden no encontrada
/usr/bin/radar-cmd.py: línea 20: ENDC: orden no encontrada
/usr/bin/radar-cmd.py: línea 22: error sintáctico cerca del elemento inesperado `('
/usr/bin/radar-cmd.py: línea 22: `def printException(e):'

**Comment by giordand** [comment]
Romina, hice una corrección en el script `radar-cmd.py` . Probablemente el error que tuviste fue a causa de que faltaba la linea `#!/usr/bin/env python` al principio. Con eso a mi me anduvo:

![image](https://cloud.githubusercontent.com/assets/8845274/22470833/2a27fa6e-e7d9-11e6-922d-1b21981dd742.png)
