### ISSUE TITLE
No genera el mosaico

### ISSUE THREAD

**Issue by RomiNahir** [INTA-Radar/radar-cmd#2]
(radar_wrap) romina@RominaM:~/Descargas/radar-cmd-master$ python radar-cmd.py -d /home/romina/Descargas/radar-cmd-master/Testing/datos/datos/Mosaico/240/ -m 2016122616200300dBZ.vol,2016122616200500dBZ.vol,2016122616204500dBZ.vol -ele 0 -var auto -img -img_type PNG

You are using the Python ARM Radar Toolkit (Py-ART), an open source
library for working with weather radar data. Py-ART is partly
supported by the U.S. Department of Energy as part of the Atmospheric
Radiation Measurement (ARM) Climate Research Facility, an Office of
Science user facility.
If you use this software to prepare a publication, please cite:
JJ Helmus and SM Collis, JORS 2016, doi: 10.5334/jors.119

[('/home/romina/Descargas/radar-cmd-master/Testing/datos/datos/Mosaico/240/2016122616200300dBZ.vol', ('dBZ', 'reflectivity', <matplotlib.colors.ListedColormap object at 0x7fd2ada71e90>, -30, 70), '/home/romina/Descargas/radar-cmd-master/Testing/datos/datos/Mosaico/240/2016122616200300dBZ'), ('/home/romina/Descargas/radar-cmd-master/Testing/datos/datos/Mosaico/240/2016122616200500dBZ.vol', ('dBZ', 'reflectivity', <matplotlib.colors.ListedColormap object at 0x7fd2ada71e90>, -30, 70), '/home/romina/Descargas/radar-cmd-master/Testing/datos/datos/Mosaico/240/2016122616200500dBZ'), ('/home/romina/Descargas/radar-cmd-master/Testing/datos/datos/Mosaico/240/2016122616204500dBZ.vol', ('dBZ', 'reflectivity', <matplotlib.colors.ListedColormap object at 0x7fd2ada71e90>, -30, 70), '/home/romina/Descargas/radar-cmd-master/Testing/datos/datos/Mosaico/240/2016122616204500dBZ')]
[('/2016122616200300dBZ.vol', ('dBZ', 'reflectivity', <matplotlib.colors.ListedColormap object at 0x7fd2ada71e90>, -30, 70), '/2016122616200300dBZ'), ('/2016122616200500dBZ.vol', ('dBZ', 'reflectivity', <matplotlib.colors.ListedColormap object at 0x7fd2ada71e90>, -30, 70), '/2016122616200500dBZ'), ('/2016122616204500dBZ.vol', ('dBZ', 'reflectivity', <matplotlib.colors.ListedColormap object at 0x7fd2ada71e90>, -30, 70), '/2016122616204500dBZ')]
('WRADLIB: Error opening Rainbow file ', '//2016122616200300dBZ.vol')
Traceback (most recent call last):
  File "radar-cmd.py", line 237, in <module>
    rr.readRadar(dirname(file) + "/", basename(file), radarVariable=radar_variable)
  File "/home/romina/Descargas/radar-cmd-master/Procesador/RainbowRadar.py", line 33, in readRadar
    self.__radar = pyart.aux_io.read_rainbow_wrl(self.__filePath + self.__fileName)
  File "/home/romina/radar_wrap/local/lib/python2.7/site-packages/pyart/aux_io/rainbow_wrl.py", line 153, in read_rainbow_wrl
    rbf = read_rainbow(filename, loaddata=True)
  File "/home/romina/radar_wrap/local/lib/python2.7/site-packages/wradlib/io.py", line 1694, in read_Rainbow
    rbdict = get_RB_header(filename)
  File "/home/romina/radar_wrap/local/lib/python2.7/site-packages/wradlib/io.py", line 1642, in get_RB_header
    raise IOError
IOError

**Comment by giordand** [comment]
Romina, fijate si la ruta` /home/romina/Descargas/radar-cmd-master/Testing/datos/datos/Mosaico/240/` existe, sobre todo si existe una carpeta `datos` dentro de `/home/romina/Descargas/radar-cmd-master/Testing/datos/`

Otra cosa, probaste el test? Fijate que en el readme hay una sección que indica como correr un test para saber si todo esta funcionando correctamente.

**Comment by giordand** [comment]
Ademas, para sacar el mosaico solo tenes que usar el parámetro `-m` pasando los nombres de los .vol con el path completo separados por coma:

`-m /home/usuario/ejemplo_1.vol,/home/usuario/ejemplo_2.vol,/home/usuario/ejemplo_3.vol`

Otras cuestiones: 

1. Cuando usas el parámetro `-d` lo que le estas pidiendo al script es que procese todos los archivos de radar que se encuentran en esa carpeta. Si ademas usas `-R` va a procesar todo lo que se encuentre en subcarpetas a partir del path indicado en `-d`.
2. El valor del parámetro `-d` no debe llevar la barra final `/`
3. Si usas los parámetros `-f` y `-d` simultáneamente el script solo va a procesar los archivos que indicas con `-f`

**Comment by RomiNahir** [comment]
Tenía problemas en las rutas, por eso no generaba bien. Lo mismo con el Test
Y quizá al mezclar el -m, -d no estaba generando bien las cosas.
Gracias, solucionado.
Cierro
